apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sayantan
  name: service-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
  verbs: ["get", "watch", "list"]
