apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sayantan-service-reader
  namespace: sayantan
subjects:
- kind: ServiceAccount
  name: sayantan-service-account 
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
