apiVersion: apps/v1
kind: Deployment
metadata:
  name:  secondservice
  namespace: sayantan
  labels:
    app:  secondservice
spec:
  selector:
    matchLabels:
      app: secondservice
  replicas: 1
  template:
    metadata:
      labels:
        app:  secondservice
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      serviceAccountName: sayantan-service-account
      containers:
      - name:  secondservice
        image:  sayantanbhadra/secondservice:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort:  8080
          name:  secondservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: svc-secondservice
  namespace: sayantan
spec:
  selector:
    app: secondservice
  type: NodePort
  ports:
  - name: secondservice
    protocol: TCP
    port: 8080
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
